### PR TITLE
Stop quads with partially bad W components from getting rendered.

### PR DESCRIPTION
**Pull request by iCatButler**
Should fix stretched textures in games like Spyro.

### CODE REVIEW

**Comment by simias** [comment]
Why only quads? Couldn't triangle theoretically have the same issue?

**Comment by twinaphex** [comment]
Big breakthrough, the skybox glitches have all been fixed.

**Comment by twinaphex** [comment]
The only issues that remain now with PGXP integration is this -

https://github.com/libretro/beetle-psx-libretro/issues/95

And the other issue is that Ridge Racer Revolution/Rage Racer don't work with PGXP enabled.

**Comment by twinaphex** [comment]
Are some textures now not being properly perspective corrected as a result of this or were there no changes there?

**Comment by iCatButler** [comment]
Triangles were already being caught if a single vertex was missing a valid `W` component and all were set to 1, effectively disabling perspective correction for those triangles.

With quads the final vertex is processed in a second iteration of the function and was not invalidating the other vertices, just itself, hence the triangle it formed part of would stretch.

@twinaphex I think I fixed Ridge Racer with an earlier change. Let me know if it isn't.

**Comment by simias** [comment]
Oh right, I forgot about that.

And I confirm that RRR still freezes as soon as I turn on PGXP during a race even with the very latest commit (b02e5afa8f089d6ed0d54b0ea3b7e4eb44dd8073).

Ridge Racer Type 4 works well however.

**Comment by twinaphex** [comment]
Yeah, Type 4 has always worked with PGXP, it's Ridge Racer Revolution/Rage Racer which are the problem.

**Comment by iCatButler** [comment]
Ah, I think it was the original Ridge Racer I tested, it was crashing in a similar way and now seems to be fixed. I'll have a look at the others.

**Comment by simias** [comment]
@iCatButler I haven't retested it with the latest commit but a few days ago the crash would go away if I removed the call to the PGXP_NCLIP (and used the native result instead), see https://github.com/libretro/beetle-psx-libretro/issues/85#issuecomment-249579767

Hope that helps.

**Comment by iCatButler** [comment]
It looks like I did fix it, but it's a bit temperamental.

The problem isn't actually NCLIP but the values of the vertices being pushed in by the GTE's Transform function. Some of them have a depth value of 0, by which the near plane distance is divided, yielding `+-inf`. This is then multiplied by the X and Y coordinates, corrupting those and leading to the massively wrong NCLIP result further down the line.

Locally I fixed it by using `min()` and `max()` macros to clamp these values to the valid range of -1024 to 1023. On merging the change the `min()` was changed to `std::min<float>`, if I make this change locally then the game freezes due to NCLIP results again.

I feel there's probably some finer point of the standard library I'm forgetting, but I'd expect them to behave pretty much the same.

**Comment by twinaphex** [comment]
You can just use the macros if you prefer, I think we have both MIN and MAX macros too inside the retro_miscellaneous.h header which you could use.

**Comment by iCatButler** [comment]
I'll try dealing with the divide by 0 first, I have a suspicion that the results are undefined, so it's probably safer to do something to avoid it in case this comes back to bite us :)

**Comment by rz5** [comment]
@iCatButler: About that min() to std::min()<float> change - I compile the MSYS2 toolchain on Windows and so does the buildbot. It was failing to compile, so I used the latter function as it was used elsewhere in the same file.

Please don't hesitate in reverting that change though.

**Comment by iCatButler** [comment]
@rz5 no problem, it's a perfectly reasonable change.

If anything I think it's highlighted something the code should be dealing with better, I'm just not sure what the correct behaviour is.

I tried mimicking what the native GTE divide function does, clamping the end results to `0x1FFFF` and setting it explicitly to that on depth values less than near/2, but that causes incorrect culling of near polygons in some cases. So I've settled on clamping depth values to a minimum of near/2 before performing the divide, it's similar to the PCSX-R integration and seems to work well.

**Pull request merged**
