### PR TITLE
Cherrypick changes done between versions 1.21.3 and 1.22.2

### PR DESCRIPTION
**Pull request by rz5**
What needs to be tested before merging:
- [ ] Check for crashes, hangs, missing music in your preferred games.

What games need to be confirmed to be working:
Games which should have music working and not hang anymore:
- [x] Grind Session;
- [x] Pitball;
- [x] Mortal Kombat Triology => does music resume after pausing and unpausing the game?;
- [ ] Roswell Conspiracies - Aliens, Myths & Legends => Any missing music?.

Games which should not hang anymore:
- [ ] Incredible Crisis => hangs without music near start of "Etsuko and the Golden Pig";
- [x] Ballerburg - Castle Chaos => hangs when starting campaign mode;
- [x] Transformers - Beast Wars Transmetals => hangs during loading screen;
- [x] Goryuujin Electro => hangs while trying to start a game;
- [ ] Colony Wars - Vengeance (Europe) => are loading screens longer than in real hardware?;
- [ ] Arc the Lad III => disc switching should be working;
- [ ] Army Men - Air Attack (Europe) => does it hang on the loading screen of mission 5?.

It would somewhat address the request of issue #487, only in terms of game compatibility.
____

@ofry @Papermanzero @saftle @twinaphex 
Hey people, I need help testing these changes. I've attached below a win64 build for those who can't clone/compile this.

[mednafen_psx_hw_libretro.zip](https://github.com/libretro/beetle-psx-libretro/files/3175558/mednafen_psx_hw_libretro.zip)

### CODE REVIEW

**Comment by twinaphex** [comment]
These 'games with hangs' - are they regressions?

**Comment by rz5** [comment]
Not regressions, they're known bugs which are fixed with the changes done between 1.21.3 and 1.22.2.

**Comment by ofry** [comment]
Is it enough to test software rendering only?

**Comment by rz5** [comment]
Yes, software renderer is enough to test.

No need to go through all possible combinations of core options.

**Comment by rz5** [comment]
I just tested Mortal Kombat Triology. I can't on either this fork or on what's available on the buildbot.

**Comment by rz5** [comment]
Pitball - Buildbot version has issues playing the Main Menu music. This fork plays it just fine.

**Comment by rz5** [comment]
Grind Session - In the buildbot version, no music in Open Skate and Training modes, hangs when you exit level. On this fork, seems to be fixed.

**Comment by rz5** [comment]
"Ballerburg - Castle Chaos" - In the buildbot version, it hangs in a black screen after the loading screen, after you start any campaign level. In this fork, there's no hang.

Curiously enough, there's something going on with this game. The image seems to be too offset towards the bottom of the screen. There is an in-game image adjustment that helps with it, fortunately.

Ballerburg - Castle Chaos (USA)-190614-211542
Ballerburg - Castle Chaos (USA)-190614-211243

**Comment by rz5** [comment]
"Transformers - Beast Wars Transmetals" - In the buildbot, when loading e.g. training mode, it hangs. In this fork, it goes past the loading screen.

**Comment by rz5** [comment]
Goryuujin Electro - In the buildbot version, after selecting any game mode, it will hang after the loading screen. On this fork, it doesn't hang.

**Comment by twinaphex** [comment]
I'm afraid I'll have to revert this - too many issues have been pointed out, CHD not working, GTE overclocking no longer working, some games crashing/hanging on BIOS screen, etc.

It will either have to be cleanly backported, or you just need to make a new upstream-compatible Mednafen PSX core that we leave unaltered from upstream. But I don't believe all this functionality is worth breaking over the few games listed here, and it might be possible to fix those without breaking all this in the process.

Sorry for having to make this executive decision, but when too many issues are pointed out, it's time to act.

**Pull request merged**
