### PR TITLE
[squash and merge] Create core option for line-to-quad hack

### PR DESCRIPTION
**Pull request by hizzlekizzle**

### CODE REVIEW

**Comment by twinaphex** [comment]
Hey @iCatButler , I asked @hunterk to take alook into implementing this so here it should be. Sorry for the delay so far!

**Comment by twinaphex** [comment]
And thanks to @hizzlekizzle for implementing this!

**Comment by Unrul3r** [comment]
What does this option do?

**Comment by hizzlekizzle** [comment]
It tunes a heuristic that detects single-line polygons and expands them into a quad instead. The aggressive mode fixes some games that were previously unplayable, like Duke Nukem and Dark Forces and fixes some effects in other games. However, it can also cause false positives that lead to funky geometry where it doesn't belong.

**Comment by Unrul3r** [comment]
@hizzlekizzle I see. Thank you for the explanation! How would I detect if a game I play needs this or not (apart from the unplayability like the ones that you've mentioned)?

**Comment by hizzlekizzle** [comment]
@Unrul3r tbh, I don't really know of any way other than just being familiar with the game(s).

**Comment by Jj0YzL5nvJ** [comment]
Didactic documentation of this hack, pros #385 and cons #407.

**Pull request merged**
