### PR TITLE
Cherrypick changes done between versions 1.21.3 and 1.22.2, version 2

### LINKED ISSUE #363: [Open GL] Arc The Lad III Disc Switch is not recognized.
Sort of a repost of my post on the forums.

Hit the disc switch point and NOTHING will cause the game to recognize disc changes.
Using a playlist, manually switching the image files.

I hit eject, return to the game, let it set, change the disc to disc 2, change back to the game, let it sit, then go back and close the disc tray. And nothing. I thought it might be my images, both discs load fine individually. But neither will allow a disc swap. I made a new image of disc 2 from my disc, made sure the SHA-1 hash matched redump. That didn’t work. Tried an image from the redump set online. That didn’t work.

Tried both software and hardware. I tried Mednafen standalone with a playlist file. Allows to boot disc 1 or 2, swapping doesn’t work. Tried PCSX-R, that didn’t work either.

On real hardware, the game reacts immediately to the disc tray opening. It will say “Please wait” while the tray is open.

That doesn’t happen at all with Mednafen, the beetle core (SW/HW) or PCSX-R PXGP
However it works in PSX 1.13. The eject CD function actually works here and allows the game to switch discs properly.

Memory Card saves 
http://www.mediafire.com/file/w99nvrupxy9qh94/CDROM_2.1.mcr
http://www.mediafire.com/file/cb9a7th8u4q51sm/CDROM_2.srm
If you wish to test, it is the first 2 save files at around level 48 in Cariote Cave. One is before the point of no return and one is at the point of no return.

Windows 7 x64
i7 950
GTX 980 388.59 drivers
Retroarch build 1.7.2 (April 13,2018)
Using the latest downloaded cores.

### PR DESCRIPTION
**Pull request by rz5**
This PR is basically the same as PR #504, which was merged and reverted.
It addresses the request made in #487 and fixes #363.

In addition to the cherrypicks, I also made sure the "GTE Overclock" core option doesn't make the emulator hang in the BIOS's PS logo, which was why #504 was reverted in the first place.

Notable changes in this PR include the above mentioned cherrypicks and:
* 'GTE Overclock' now makes `PS_CPU::ReadInstruction()` take 1 cycle instead of 0, to prevent the hanging in the BIOS's PS logo;
* 'GTE Overclock' now reduces even more memory access/instruction read latencies to 1 cycle. Game compatibility should in theory be the same or lower and game performance should be marginally higher when the option is on;
* In mednafen/psx/gte.cpp, `stdint.h` types have been used in favor of other aliases, style nits were applied. Some code was refactored to use less/smaller temp variables. 
* The NCLIP function had a bug caused by https://github.com/libretro/beetle-psx-libretro/commit/71f1c9a7f7a247f74ef07ab50d0e15b9825934af#diff-2b2c9e251725122a05a2cc3c22a0b33bR1449-R1454, because the intermediate `sum` variable was 32-bit and should have been 64-bit to check for 32-bit overflow. Commit https://github.com/libretro/beetle-psx-libretro/commit/ce9d7d8aeb7f8dea23635f1e9e7eb82deb7d021b fixes this by completely ignoring the intermediate variables and redoing calculations in the same way as upstream...so I cleaned that up and NCLIP-related bugs and AmiDog's GTE tests didn't show regressions with these refactors;
* Style nites to various files and Makefiles;
* All ugui files were moved to the deps folder, makes sense to be from an organization point of view.

### CODE REVIEW

**Comment by rz5** [comment]
@ggdrt - Tagged you for a review. Whenever you have the time, I would appreciate any criticism you could offer. 
And if you can test this PR, that would be a big bonus for me.

In hindsight, the style nits and the NCLIP refactor should have been separate PRs but oh well.

**Comment by twinaphex** [comment]
@ggdrt Hi there, are you still intent on checking this out?

**Comment by simias** [comment]
As a side note, when we enable these types of hacks to effectively make the CPU timings less accurate on purpose we could also disable the emulation of some things that mostly end up wasting resources, in particular:

* icache emulation

Should be easy to implement by forcing the emulator to enter this branch (which is normally called when the icache is disabled or the memory access is done through an uncached section):
https://github.com/libretro/beetle-psx-libretro/blob/18a9de19f3f079408eb8181aa4c5144e9434c5f7/mednafen/psx/cpu.cpp#L507

Beyond performance considerations disabling the icache will break a small handful of games but it shouldn't be too bad, after all dynarecs don't emulate the icache either and they have decent compatibility.

* Everything having to do with LDAbsorb/ReadAbsorb

Assuming that you also inhibit this line which will remove any memory load latency:

https://github.com/libretro/beetle-psx-libretro/blob/18a9de19f3f079408eb8181aa4c5144e9434c5f7/mednafen/psx/cpu.cpp#L410

Although that might be overdoing it a bit, at this point the CPU will run *a lot* faster than native.

_The manufacturer denies all responsibility in case of damage inflicted upon people or goods as a result of a bad installation or incorrect use of the device._

**Comment by rz5** [comment]
@simias I tried what you suggested in terms of skipping icache emulation when reading instructions in a sepparate branch: https://github.com/libretro/beetle-psx-libretro/commit/f1188c2c45608dc66ff8f38009a7a8cb5b23a673

What I've noticed while testing GT2 and THPS2 is that:
With stock settings but forcing that fast path in `ReadInstruction`, the internal framerate seems to be halved but the fastforward framerate is doubled. I initially only noticed the fastforward framerate and was surprised at the doubling but then I noticed the render rate halved and wasn't as happy about it.

Combining that hack with the GTE OC hack, the internal framerate is no longer halved and the fastforward framerate is hit or miss; it either increases slightly (THPS2) or decreases slightly (GT2).

**Comment by rz5** [comment]
I've been asked to re-test this, so...after turning most of the hacks/"enhancements" on and noticing the PS log hang again, I decided to do a recap on where this PR is in terms of what's broken relative to the master branch:

When applying the CDC upstream changes (https://github.com/libretro/beetle-psx-libretro/pull/582/commits/61a6a87da4f42a9507ea91ed1b8007687cff4401), if you set `CPU Frequency Scaling (Overclock)` higher than 270%, the BIOS will **hang on the PS logo** while the master branch won't hang even if it's set to 500% . I don't know if or how this can be fixed.

Enabling the `GTE Overclock` option alone would also cause the hang.
I did some brute force testing, disabling lines of code one by one till I found the culprit (https://github.com/libretro/beetle-psx-libretro/pull/582/commits/a061c3151e4e10ec3b435bc9a4c59c7b3875c42c).  However, re-testing this commit, GTE OC with CPU OC >250% will cause the hang. **The master branch won't hang with GTE OC on and CPU set to 500%**.

Because I had found the offending line, I went for more aggressive changes to the GTE OC (https://github.com/libretro/beetle-psx-libretro/pull/582/commits/0af31a6f189ebc52eef8d6288e64cbdf204c9a8c). Turning it on by itself won't cause the hang and internal FPS might be higher/more stable. But now, GTE OC with CPU OC >110% will.

The best I managed to do was undo was incorporate some of simias's feedback such that GTE OC and CPU OC <250% don't cause the hang.

I would like to prioritize keeping this codebase fresh with upstream and maximize game compatibility. If I did take the initiative to merge this PR, users would inevitably file bug reports about the above limitations and it would get reverted again because working speedhacks would be favored over compatibility.

So that's where this PR is at. I'm at my limit in terms of what I know about this codebase and PSX emulation in general (which is not much, to be honest) and in terms of how much testing I'm willing to do.

**Comment by twinaphex** [comment]
@simias Given this roadblock that @rz5 ran into, could you help us basically getting GTE Overclocking and CPU overclocking to work reliably again with these cherrypicked upstream commits? Otherwise we keep having to hold these patches back since lots of users would be complaining about these beneficial features no longer working, whereas we really want to be moving forward here as well in terms of accuracy and compatibility. Put short, we really need your help here.

**Comment by simias** [comment]
@rz5 if I remember correctly I had also implemented some CD overclocking code, does overclocking CPU *and* CD improve the situation?

Beyond that I'm currently digging deeper than ever into mednafen PSX 1.24.0 for a nefarious project of my own, but unfortunately I haven't reached the CD subsystem yet. Fingers crossed I'll get there in the not so far future, at which point I may have enough insights to figure out what's happening and how to fix it.

If you want to try debugging it on your side here's what I'd do:

* Add debugging code on the calls for the various CD commands:

https://github.com/libretro/beetle-psx-libretro/blob/18a9de19f3f079408eb8181aa4c5144e9434c5f7/mednafen/psx/cdc.cpp#L2417-L2453

* Compare the call sequence with and without overclock to figure out where it's stalling exactly

* And then... I guess look for inspiration.

When I was working on Rustation I encountered a few timing issues when the CPU was too fast, the BIOS is rather poorly coded and often uses hardcoded busyloops when waiting for an event instead of polling the hardware properly. If the CPU is too fast while the rest of the hardware remains at the normal speed it's possible that it just times out waiting for something to happen. But if that's the case it's odd that it didn't happen previously, *unless* the new version increased the CD latency in some situations somehow.

Looking at the diff I see that there've been many deep changes in the CDC code, and in particular the timings, for instance:

**Comment by rz5** [comment]
@simias Thanks for chiming in.

For context, the one line you linked that has increased latency may be related to this comment on the upstream changelog:
> PSX: Altered seek and pause timing and behavior per tests on a PS1; fixes hangs in "Incredible Crisis", "Ballerburg - Castle Chaos", "Transformers - Beast Wars Transmetals", and "Simple 1500 Series Vol. 057 - The Maze".

I can only assume that increased latency is required timing to get past the hangs on those games.

Here's a trace of CDC commands recorded during boot, with MODE_SPEED also being tracked plus calls to PreSeekHack and calls to the CDIF's ReadSector functions...brace for impact:
```
[CDC] Command: Test | MODE_SPEED: 0
[CDC] Command: Nop | MODE_SPEED: 0
[CDC] Command: Nop | MODE_SPEED: 0
[CDC] Command: ID | MODE_SPEED: 0
[CDC] Command: ReadTOC | MODE_SPEED: 0
[CDC] Command: Nop | MODE_SPEED: 0
[CDC] Command: ID | MODE_SPEED: 0
[CDC] Command: Setloc | MODE_SPEED: 0
[CDC] Command: SeekL | MODE_SPEED: 0
[CDC] PreSeekHack: target = (4)
        [CDIF] ReadRawSectorPwOnly: LBA 4
        [CDIF] ReadRawSector: LBA 4
        [CDIF] ReadRawSector: LBA 5
        [CDIF] ReadRawSector: LBA 6
[CDC] Command: Setmode | MODE_SPEED: 0
[CDC] Command: ReadN | MODE_SPEED: 128
[CDC] PreSeekHack: target = (4)
        [CDIF] ReadRawSectorPwOnly: LBA 4
        [CDIF] ReadRawSector: LBA 4
        [CDIF] ReadRawSector: LBA 5
        [CDIF] ReadRawSector: LBA 6
[CDC] Command: Pause | MODE_SPEED: 128
        [CDIF] ReadRawSector: LBA 4
        [CDIF] ReadRawSector: LBA 5
        [CDIF] ReadRawSector: LBA -3
[libretro WARN] Attempt to read LBA -3, >= LBA 292651
[INFO] [Environ]: SET_MESSAGE: Slow CD image read detected -- consider using async or precache CD Access Method
        [CDIF] ReadRawSector: LBA -3
[libretro WARN] Attempt to read LBA -3, >= LBA 292651
        [CDIF] ReadRawSector: LBA -2
[libretro WARN] Attempt to read LBA -2, >= LBA 292651
        [CDIF] ReadRawSector: LBA -1
[libretro WARN] Attempt to read LBA -1, >= LBA 292651
        [CDIF] ReadRawSector: LBA 0
        [CDIF] ReadRawSector: LBA 1
        [CDIF] ReadRawSector: LBA 2
        [CDIF] ReadRawSector: LBA 3
        [CDIF] ReadRawSector: LBA 4
        [CDIF] ReadRawSector: LBA 5
        [CDIF] ReadRawSector: LBA -3
[libretro WARN] Attempt to read LBA -3, >= LBA 292651
        [CDIF] ReadRawSector: LBA -2
[libretro WARN] Attempt to read LBA -2, >= LBA 292651
        [CDIF] ReadRawSector: LBA -1
[libretro WARN] Attempt to read LBA -1, >= LBA 292651
        [CDIF] ReadRawSector: LBA 0
        [CDIF] ReadRawSector: LBA 1
        [CDIF] ReadRawSector: LBA 2
        [CDIF] ReadRawSector: LBA 3
        [CDIF] ReadRawSector: LBA 4
        [CDIF] ReadRawSector: LBA 5
        [CDIF] ReadRawSector: LBA -3
[libretro WARN] Attempt to read LBA -3, >= LBA 292651
        [CDIF] ReadRawSector: LBA -2
[libretro WARN] Attempt to read LBA -2, >= LBA 292651
        [CDIF] ReadRawSector: LBA -1
[libretro WARN] Attempt to read LBA -1, >= LBA 292651
        [CDIF] ReadRawSector: LBA 0
        [CDIF] ReadRawSector: LBA 1
        [CDIF] ReadRawSector: LBA 2
        [CDIF] ReadRawSector: LBA 3
        [CDIF] ReadRawSector: LBA 4
        [CDIF] ReadRawSector: LBA 5
        [CDIF] ReadRawSector: LBA -3
[libretro WARN] Attempt to read LBA -3, >= LBA 292651
        [CDIF] ReadRawSector: LBA -2
[libretro WARN] Attempt to read LBA -2, >= LBA 292651
[CDC] Command: Setloc | MODE_SPEED: 128
[CDC] Command: SeekL | MODE_SPEED: 128
[CDC] PreSeekHack: target = (5)
        [CDIF] ReadRawSectorPwOnly: LBA 5
        [CDIF] ReadRawSector: LBA 5
        [CDIF] ReadRawSector: LBA 6
        [CDIF] ReadRawSector: LBA 7
[CDC] Command: Setmode | MODE_SPEED: 128
        [CDIF] ReadRawSector: LBA -1
[libretro WARN] Attempt to read LBA -1, >= LBA 292651
[CDC] Command: ReadN | MODE_SPEED: 128
[CDC] PreSeekHack: target = (5)
        [CDIF] ReadRawSectorPwOnly: LBA 5
        [CDIF] ReadRawSector: LBA 5
        [CDIF] ReadRawSector: LBA 6
        [CDIF] ReadRawSector: LBA 7
        [CDIF] ReadRawSector: LBA 8
        [CDIF] ReadRawSector: LBA 9
        [CDIF] ReadRawSector: LBA 10
        [CDIF] ReadRawSector: LBA 11
        [CDIF] ReadRawSector: LBA 12
        [CDIF] ReadRawSector: LBA 13
[CDC] Command: Pause | MODE_SPEED: 128
        [CDIF] ReadRawSector: LBA 10
        [CDIF] ReadRawSector: LBA 11
        [CDIF] ReadRawSector: LBA 3
        [CDIF] ReadRawSector: LBA 4
        [CDIF] ReadRawSector: LBA 5
        [CDIF] ReadRawSector: LBA 6
        [CDIF] ReadRawSector: LBA 7
        [CDIF] ReadRawSector: LBA 8
        [CDIF] ReadRawSector: LBA 9
        [CDIF] ReadRawSector: LBA 10
        [CDIF] ReadRawSector: LBA 11
        [CDIF] ReadRawSector: LBA 3
        [CDIF] ReadRawSector: LBA 4
        [CDIF] ReadRawSector: LBA 5
        [CDIF] ReadRawSector: LBA 6
        [CDIF] ReadRawSector: LBA 7
        [CDIF] ReadRawSector: LBA 8
        [CDIF] ReadRawSector: LBA 9
        [CDIF] ReadRawSector: LBA 10
        [CDIF] ReadRawSector: LBA 11
        [CDIF] ReadRawSector: LBA 3
        [CDIF] ReadRawSector: LBA 4
        [CDIF] ReadRawSector: LBA 5
        [CDIF] ReadRawSector: LBA 6
        [CDIF] ReadRawSector: LBA 7
        [CDIF] ReadRawSector: LBA 8
        [CDIF] ReadRawSector: LBA 9
        [CDIF] ReadRawSector: LBA 10
        [CDIF] ReadRawSector: LBA 11
[CDC] Command: ID | MODE_SPEED: 128
[CDC] Command: Reset | MODE_SPEED: 128
[CDC] PreSeekHack: target = (0)
        [CDIF] ReadRawSectorPwOnly: LBA 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] Command: Reset | MODE_SPEED: 0
        [CDIF] ReadRawSector: LBA 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] PreSeekHack: target = (0)
        [CDIF] ReadRawSectorPwOnly: LBA 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] Command: Reset | MODE_SPEED: 0
        [CDIF] ReadRawSector: LBA 0
        [CDIF] ReadRawSector: LBA 1
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] PreSeekHack: target = (0)
        [CDIF] ReadRawSectorPwOnly: LBA 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] Command: Reset | MODE_SPEED: 0
        [CDIF] ReadRawSector: LBA 0
        [CDIF] ReadRawSector: LBA 1
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] PreSeekHack: target = (0)
        [CDIF] ReadRawSectorPwOnly: LBA 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] Command: Reset | MODE_SPEED: 0
        [CDIF] ReadRawSector: LBA 0
        [CDIF] ReadRawSector: LBA 1
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] PreSeekHack: target = (0)
        [CDIF] ReadRawSectorPwOnly: LBA 0
        [CDIF] ReadRawSector: LBA 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] PreSeekHack: target = (0)
        [CDIF] ReadRawSectorPwOnly: LBA 0
[CDC] Command: Reset | MODE_SPEED: 0
        [CDIF] ReadRawSector: LBA 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] PreSeekHack: target = (0)
        [CDIF] ReadRawSectorPwOnly: LBA 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] Command: Reset | MODE_SPEED: 0
        [CDIF] ReadRawSector: LBA 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] PreSeekHack: target = (0)
        [CDIF] ReadRawSectorPwOnly: LBA 0
        [CDIF] ReadRawSector: LBA 0
[CDC] Command: Reset | MODE_SPEED: 0
[CDC] PreSeekHack: target = (0)
        [CDIF] ReadRawSectorPwOnly: LBA 0
        [CDIF] ReadRawSector: LBA 0
        [CDIF] ReadRawSector: LBA 1
[CDC] Command: Reset | MODE_SPEED: 0
(...)
```

It will keep repeating that reset command with the same mode if nothing is done. If the core option that causes the hang is turned off, then eventually we'll get this showing up:

```
[CDC] Command: Reset | MODE_SPEED: 0
        [CDIF] ReadRawSector: LBA 0
        [CDIF] ReadRawSector: LBA 1
        [CDIF] ReadRawSector: LBA 2
        [CDIF] ReadRawSector: LBA -6
[libretro WARN] Attempt to read LBA -6, >= LBA 292651
        [CDIF] ReadRawSector: LBA -5
[libretro WARN] Attempt to read LBA -5, >= LBA 292651
        [CDIF] ReadRawSector: LBA -4
[libretro WARN] Attempt to read LBA -4, >= LBA 292651
        [CDIF] ReadRawSector: LBA -3
[libretro WARN] Attempt to read LBA -3, >= LBA 292651
        [CDIF] ReadRawSector: LBA -2
[libretro WARN] Attempt to read LBA -2, >= LBA 292651
        [CDIF] ReadRawSector: LBA -1
[libretro WARN] Attempt to read LBA -1, >= LBA 292651
        [CDIF] ReadRawSector: LBA 0
        [CDIF] ReadRawSector: LBA 1
[CDC] Command: Setloc | MODE_SPEED: 0
[CDC] Command: SeekL | MODE_SPEED: 0
[CDC] PreSeekHack: target = (16)
        [CDIF] ReadRawSectorPwOnly: LBA 16
        [CDIF] ReadRawSector: LBA 16
        [CDIF] ReadRawSector: LBA 17
        [CDIF] ReadRawSector: LBA 18
[CDC] Command: Setmode | MODE_SPEED: 0
[CDC] Command: ReadN | MODE_SPEED: 128
[CDC] PreSeekHack: target = (16)
        [CDIF] ReadRawSectorPwOnly: LBA 16
        [CDIF] ReadRawSector: LBA 16
        [CDIF] ReadRawSector: LBA 17
        [CDIF] ReadRawSector: LBA 18
[CDC] Command: Pause | MODE_SPEED: 128
        [CDIF] ReadRawSector: LBA 16
        [CDIF] ReadRawSector: LBA 17
        [CDIF] ReadRawSector: LBA 9
        [CDIF] ReadRawSector: LBA 10
        [CDIF] ReadRawSector: LBA 11
(...)
```

The CD interface being used is the multithreaded one...doesn't this smell like a race condition?

**Comment by ggdrt** [comment]
@rz5 Is this currently safe to merge in or does this require more work?

**Comment by rz5** [comment]
> 
> 
> @rz5 Is this currently safe to merge in or does this require more work?

@ggdrt - No, unfortunately this is still a work in progress PR. Game compatibility would be higher than it is now and match standalone mednafen. But the CDC changes - which constitute the majority of it - would in turn limit or break features like CPU frequency scaling and "GTE overclocking". And I don't know enough about this codebase and PSX emulation in general to fix that breakage.

Because I prioritize compatibility over speedhacks, I'd be in favor of merging this. But, specifically on this topic, it's not me who decides it.

**Comment by Mr-Jake** [comment]
If the current core can't be updated, maybe it would make sense to split it. The current core could stay as is with the speedhacks and be perhaps renamed to beetle-psx-libretro-fast. Then the other beetle-psx-libretro core would focus on the latest updates making it more accurate and compatible, removing the speedhacks. Just a suggestion.

**Comment by i30817** [comment]
In effect that would be 'return of mednafen software retroarch port mk2' because upstream code has no hardware renderer and if you're going to remove hacks (like pgxp) you might as well remove everything.

**Comment by twinaphex** [comment]
Under no circumstance will the hardware renderers or any of the numerous improvements/additions to Mednafen PSX ever be removed. That's just throwing the baby out with the bathwater.

Just create a separate core that sticks closely to upstream I gues, Beetle PSX needs to be its own thing.

**Comment by dankcushions** [comment]
closed during hack-gate 2020. @twinaphex please re-open :)

**Pull request closed without merging**
