### PR TITLE
Removed library path to /usr/local/lib.

### PR DESCRIPTION
**Pull request by dev-0x7C6**
I'm getting QA problems in my sandbox cross-compilation environment that /usr/local/lib is pointing to host libraries.

ERROR: beetle-psx-libretro-1.0+gitrAUTOINC+7210cff299-r100 do_package_qa: QA Issue: beetle-psx-libretro: The compile log indicates that host include and/or library paths were used.
         Please check the log '/home/dev/embedded/retro-build-enviroment/build/tmp/work/core2-32-poky-linux/beetle-psx-libretro/1.0+gitrAUTOINC+7210cff299-r100/temp/log.do_compile' for more information. [compile-host-path]

### CODE REVIEW

**Comment by rz5** [comment]
The change in this PR will likely break builds on FreeBSD: https://github.com/libretro/beetle-psx-libretro/commit/a743392186d7883370c9b307c07991770fab0707

**Comment by dev-0x7C6** [comment]
@rz5 I guess you maybe right, but this looks suspicious.

@bparker06 Is this a common case in FreeBSD to have OpenGL libraries in /usr/local/lib? Can we remove those hard-coded paths?

**Comment by Jj0YzL5nvJ** [comment]
I don't know how FreeBSD works, but on Linux, OpenGL libraries are generally configured from ldconfig.
`/etc/ld.so.conf.d/i386-linux-gnu_GL.conf`
`/etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf`

I normally use said path (`LDFLAGS="-L/usr/local/lib"`) to compile and install programs outside of package manager. But it's not always the case.
The fact that such "fixed" path is arbitrary imposed in such a way. It can potentially screw up many more users than it could help. Mainly n00bs, advanced users will simply use their own solution. Like I do, and I'm not _advanced_.

**Comment by dev-0x7C6** [comment]
I think we can merge this. Hardcoded include path that was introduced in a743392 is no longer there.

**Comment by dankcushions** [comment]
closed during hack-gate 2020. @twinaphex please re-open :)

**Pull request closed without merging**
