### PR TITLE
Performance Fixes for Savestates + Fast Savestates

### PR DESCRIPTION
**Pull request by Dwedit**
* Savestate Performance Fix - no longer does giant memory allocations and copies
* Loadstate Performance Fix - no longer does N^2 string comparisons
* Fast Savestates (excludes text labels from the savestates, 20% speedup)
* Minor Savestate Performance Fix, no longer uses snprintf when strncpy will do.  Only applies to the text labels, no effect on fast savestates.

### CODE REVIEW

**Comment by twinaphex** [comment]
Some early testing results - performance is great so far but some display issues -

Wipeout (USA) - with runahead set to 1 frame, afte the loading screen no output image is shown. You have to disable runahead for the frame to be non-black again.

Tekken 2 (USA) - runs fine and looks fine except for during loading screens, which seem to be glitched out. This is with runahead set to 1 frame.

Tekken 3 (USA) - runs fine and looks fine except for during loading screens which seem to be glitched out. This is with runahead set to 1 frame.

Is this a case of not having runahead frames set properly or are there more audio/video disable tweaks left to be added?

**Comment by Dwedit** [comment]
There are still issues with runahead and the GL renderer.  I've seen the entire retroarch menu system even disappear with Runahead turned on.  Software renderer seems fine for now.

I haven't added any of the audio/video disable tweaks yet.

**Comment by fr500** [comment]
Maybe make fast saves an option instead of runahead only?
It could probably help with netplay.

**Comment by Dwedit** [comment]
RetroArch's Netplay and Rewind features could request fast savestates easily enough.

**Comment by fr500** [comment]
I tested this by forcing UsingFastStates to return true all the time

```diff
$ git diff
diff --git a/libretro.cpp b/libretro.cpp
index a838954..befd5ac 100644
--- a/libretro.cpp
+++ b/libretro.cpp
@@ -3929,9 +3929,9 @@ bool UsingFastSavestates()
    int flags;
    if (environ_cb(RETRO_ENVIRONMENT_GET_AUDIO_VIDEO_ENABLE, &flags))
    {
-      return flags & 4;
+      return true & 4;
    }
-   return false;
+   return true;
 }

 bool retro_serialize(void *data, size_t size)
@@ -3951,7 +3951,7 @@ bool retro_serialize(void *data, size_t size)
       //fast save states are at least 20% faster
       FastSaveStates = UsingFastSavestates();
       bool ret = MDFNSS_SaveSM(&st, 0, 0, NULL, NULL, NULL);
-      FastSaveStates = false;
+      FastSaveStates = true;
       return ret;
    }
    else
@@ -3983,7 +3983,7 @@ bool retro_serialize(void *data, size_t size)

       FastSaveStates = UsingFastSavestates();
       ret = MDFNSS_SaveSM(&st, 0, 0, NULL, NULL, NULL);
-      FastSaveStates = false;
+      FastSaveStates = true;

       memcpy(data, st.data, size);
       free(st.data);
@@ -4004,7 +4004,7 @@ bool retro_unserialize(const void *data, size_t size)
    //fast save states are at least 20% faster
    FastSaveStates = UsingFastSavestates();
    bool okay = MDFNSS_LoadSM(&st, 0, 0);
-   FastSaveStates = false;
+   FastSaveStates = true;
    return okay;
 }

diff --git a/libretro_options.h b/libretro_options.h
index 48d8f98..49f5e42 100644
--- a/libretro_options.h
+++ b/libretro_options.h
@@ -2,7 +2,7 @@
 #ifdef HAVE_HW
 #define MEDNAFEN_CORE_NAME "Beetle PSX HW"
 #else
-#define MEDNAFEN_CORE_NAME "Beetle PSX"
+#define MEDNAFEN_CORE_NAME "Beetle PSXX"
 #endif
 #define MEDNAFEN_CORE_VERSION "0.9.44.1"
 #define MEDNAFEN_CORE_EXTENSIONS "exe|cue|toc|ccd|m3u|pbp|chd"
```
but I don't see a dramatic improvement at all using rewind or netplay

```
| rewind off | rewind on | rewind on fast states
| 110fps     | 83fps     | 84fps
```

**Pull request merged**
