### PR TITLE
Fixes for filtered texture rendering

### PR DESCRIPTION
**Pull request by amoser**
Fixes for issues highlighted in the attached "before" and "after" images.

before
after

### CODE REVIEW

**Comment by twinaphex** [comment]
Thank you, that looks like a big improvement! Well done!

**Comment by hizzlekizzle** [comment]
This is great! Does it close this issue out, as well? https://github.com/libretro/beetle-psx-libretro/issues/648

**Comment by backgamon** [comment]
For me it's not work :/
retroarch 2020-07-27 20-13-45-654
retroarch 2020-07-27 20-13-50-932

**Comment by amoser** [comment]
> 
> 
> For me it's not work :/
> retroarch 2020-07-27 20-13-45-654
> retroarch 2020-07-27 20-13-50-932

Did you run the rebuild shaders script in the glsl folder? Just running make doesn't seem to capture those changes. 

Not that I'm ruling out the possibility that I made some kind of terrible mistake when making this pull request (like forgetting a file or something) -- let me triple check!

**Comment by backgamon** [comment]
Rebuilding shaders make it work, good job!
At least now Psx Beetle are the best Psx emu so far :)
retroarch 2020-07-28 10-26-42-255

**Comment by twinaphex** [comment]
@amoser Can you please commit these re-generated shaders? Unless I'm misunderstanding something, if it's the glslc-based shaders that parallel psx uses, users shouldn't really be expected to have to do that manually, the emulator should already have the latest up-to-date generated shaders in its core code.

**Comment by amoser** [comment]
> 
> 
> @amoser Can you please commit these re-generated shaders? Unless I'm misunderstanding something, if it's the glslc-based shaders that parallel psx uses, users shouldn't really be expected to have to do that manually, the emulator should already have the latest up-to-date generated shaders in its core code.

I can do that for sure, if it helps! To be clear, my expectation certainly wasn't for users to need to do anything when just running a compiled binary of the emulator -- I had assumed (perhaps naively) that that the automated build system would also recompile any out-of-date shaders, and that manually running the rebuild_shaders.sh script would only be ever be necessary when building the entire core from source (which is what I assumed backgamon was doing). 

The fact that the pre-compiled shaders are included in the repo _along with_ their respective source code probably was a hint that they might need to be committed as well in order to stay up-to-date.

So if I'm understanding this correctly, I should make an additional commit which includes the _compiled_ versions of the modified shaders, which are located in "parallel-psx\glsl\prebuilt" . Sorry for any inconvenience, and please let me know if this still doesn't sound like what you're expecting.

**Comment by twinaphex** [comment]
No need to apologize.

And yes, that sounds fine - just regenerate the shaders so the 'prebuilt' shaders are updated and committed in a separate PR.

**Comment by amoser** [comment]
Done.

**Pull request merged**
