### PR TITLE
Scaled read (fix performance regression)

### PR DESCRIPTION
**Pull request by xzn**
Two changes:

ac16efd  avoid dividing by FB_SIZE which is slow, multiply by SCALE and use texelFetch instead.

b162646 [fixed a bug](https://github.com/libretro/beetle-psx-libretro/commit/b16264646dd494e8f97a7aed9f2ccf6b3a9df78c#diff-5dfb22247554410c870c7ddc6a7069aeR2013) where scaled_read variable was not updated in inner loop.

Should fix performance regression introduced by #716

### CODE REVIEW

**Comment by twinaphex** [comment]
Let me know when this is ready to be merged.

**Comment by xzn** [comment]
b162646 should fix #720 for the Vulkan case (my fault for the regression)

6124a06 fix some additional flickering, not sure what the performance penalties are; quick test doesn't show much impact.

**Comment by xzn** [comment]
Something might as well discuss here:

Both [this](https://github.com/libretro/beetle-psx-libretro/blob/master/parallel-psx/renderer/renderer.cpp#L1747) and [this](https://github.com/libretro/beetle-psx-libretro/blob/master/parallel-psx/renderer/renderer.cpp#L1794) conditions are different than what's in [`select_pipeline`](https://github.com/libretro/beetle-psx-libretro/blob/master/parallel-psx/renderer/renderer.cpp#L1579)

Wouldn't there be cases where a primitive is queued for both `semi_transparent_opaque` and `semi_transparent`? Or is that how it's intended to work? From a quick glance the gl code and duckstation doesn't work this way.

Specifically if a primitive is both textured and semi-transparent, then it's put in both queue.

While on the subject what exactly is `semi_transparent_opaque`? How is it intended to be different from `semi_transparent`?

Pardon my confusion :o

**Comment by xzn** [comment]
Also regarding this [comment](https://github.com/libretro/beetle-psx-libretro/pull/716#issuecomment-691122808),

The problem I have right now is that I'm generating about 10 to 20 megabytes of shader code. The code in `renderer.cpp` that will make use of all the different shader combinations will also gets quite complicated.

If I introduce compression to get down the binary size it'll complicate the code further.

Any good idea on how to proceed? (Introducing `glslang` as a runtime dependency could be an option but it also increases binary size, as well as load time)

**Comment by xzn** [comment]
In my previous PR [this code](https://github.com/libretro/beetle-psx-libretro/blob/d057a30e74fcee86757084804ec199b2c8e2a757/parallel-psx/renderer/renderer.cpp#L1414) doesn't handle orientation at all. 

I made some changes in 8ecc2bc  to workaround this.

**Comment by twinaphex** [comment]
> The problem I have right now is that I'm generating about 10 to 20 megabytes of shader code. The code in renderer.cpp that will make use of all the different shader combinations will also gets quite complicated.

> If I introduce compression to get down the binary size it'll complicate the code further.

> Any good idea on how to proceed? (Introducing glslang as a runtime dependency could be an option but it also increases binary size, as well as load time)

Hmm, let me propose this to someone who likely knows best how to proceed.

**Pull request merged**
