### PR TITLE
Update JINC2 to prevent NaN, which result in black texture in some cases

### PR DESCRIPTION
**Pull request by xzn**
Discovered this when messing around with vertex shader to center pixel to screen coordinates. JINC2 filter would result in black textures in some cases.

This change resolves it.

### CODE REVIEW

**Comment by rz5** [comment]
Could you please share some visual examples of what is fixed?

**Comment by xzn** [comment]
Sure:

I'm modifying the vertex shader (for testing) to be like [Duckstation](https://github.com/stenzek/duckstation/blob/9254fc9e639af88cc972ac1c55d7b773b3afbecb/src/core/gpu_hw_shadergen.cpp#L534).

So the ground texture in this game looks normal:
image

Example of NaN when JINC2 is enabled:

image
image

This wouldn't happen before because vertex coordinate wasn't aligned with uv exactly like that. (I believe that's why anyhow)

If zero check is not handled per component wise then the dot product and other stuff that follows all result in NaN.

**Comment by hizzlekizzle** [comment]
this looks good to me. Do we need to update the vulkan shaders accordingly, as well?

**Comment by xzn** [comment]
Sorry totally forgot there's OpenGL as well. Added the change

**Pull request merged**
